version: '3'
services:
  postgres:
    container_name: challenge-idwall-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5445:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    container_name: challenge-idwall-backend
    image: challenge-idwall-backend:v.1.0.2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src/main:/app/src/main

# mvn package            (Generated as new .jar)
# docker build -t [name] . (Generated as new image)

# docker-compose up      (Create new network)
# docker-compose up -d   (Recreated as new docker image)
# docker-compose down    (Delete as network)
# docker-compose stop    (Stop as network)