##############
## DATABASE ##
##############
spring:
  datasource:
    url:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME_EMAIL}
    password: ${USER_NAME_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true